name: EternalNature
main: me.masstrix.eternalnature.EternalNature
version: ${project.version}
author: Masstrix
api-version: 1.19
website: https://github.com/Masstrix/Eternal-Nature

softdepend: [PlaceholderAPI]

commands:
  eternalnature:
    aliases:
      - en
    permission: "eternalnature.cmd.admin"
  hydrate:
    permission: "eternalnature.cmd.hydrate"